name: CI - Lint e Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Executar Linter
        run: npm run lint -- --no-error-on-unmatched-pattern

      - name: Compilar o projeto
        run: npm run build